import { Html, Head, Preview, Body, Container, Section, Heading, Text, Hr } from '@react-email/components';
import * as React from 'react';
const AdminSecurityAlertEmail = ({ alertType, time, description }) => (React.createElement(Html, null,
    React.createElement(Head, null),
    React.createElement(Preview, null,
        "C\u1EA3nh b\u00E1o b\u1EA3o m\u1EADt: ",
        alertType),
    React.createElement(Body, { style: { background: '#f9f9f9', fontFamily: 'Arial, sans-serif' } },
        React.createElement(Container, { style: { maxWidth: 600, margin: '0 auto', background: '#fff', borderRadius: 8, padding: 24 } },
            React.createElement(Section, { style: { textAlign: 'center' } },
                React.createElement(Heading, null, "C\u1EA3nh b\u00E1o b\u1EA3o m\u1EADt h\u1EC7 th\u1ED1ng"),
                React.createElement(Text, null,
                    "Lo\u1EA1i c\u1EA3nh b\u00E1o: ",
                    React.createElement("b", null, alertType)),
                React.createElement(Text, null,
                    "Th\u1EDDi gian: ",
                    time)),
            React.createElement(Section, null,
                React.createElement(Text, null,
                    React.createElement("b", null, "M\u00F4 t\u1EA3:"),
                    " ",
                    description)),
            React.createElement(Hr, null),
            React.createElement(Section, null,
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "Vui l\u00F2ng ki\u1EC3m tra h\u1EC7 th\u1ED1ng v\u00E0 x\u1EED l\u00FD k\u1ECBp th\u1EDDi."),
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "M\u1ECDi th\u1EAFc m\u1EAFc li\u00EAn h\u1EC7: support@sportstore.com"))))));
export default AdminSecurityAlertEmail;
