import { Html, Head, Preview, Body, Container, Section, Heading, Text, Hr } from '@react-email/components';
import * as React from 'react';
const AdminNewUserEmail = ({ userName, email, time }) => (React.createElement(Html, null,
    React.createElement(Head, null),
    React.createElement(Preview, null,
        "Ng\u01B0\u1EDDi d\u00F9ng m\u1EDBi \u0111\u0103ng k\u00FD: ",
        userName),
    React.createElement(Body, { style: { background: '#f9f9f9', fontFamily: 'Arial, sans-serif' } },
        React.createElement(Container, { style: { maxWidth: 600, margin: '0 auto', background: '#fff', borderRadius: 8, padding: 24 } },
            React.createElement(Section, { style: { textAlign: 'center' } },
                React.createElement(Heading, null, "Ng\u01B0\u1EDDi d\u00F9ng m\u1EDBi \u0111\u0103ng k\u00FD"),
                React.createElement(Text, null,
                    "T\u00EAn: ",
                    React.createElement("b", null, userName)),
                React.createElement(Text, null,
                    "Email: ",
                    React.createElement("b", null, email)),
                React.createElement(Text, null,
                    "Th\u1EDDi gian \u0111\u0103ng k\u00FD: ",
                    time)),
            React.createElement(Hr, null),
            React.createElement(Section, null,
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "Vui l\u00F2ng ki\u1EC3m tra v\u00E0 x\u00E1c th\u1EF1c t\u00E0i kho\u1EA3n n\u1EBFu c\u1EA7n."),
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "M\u1ECDi th\u1EAFc m\u1EAFc li\u00EAn h\u1EC7: support@sportstore.com"))))));
export default AdminNewUserEmail;
