import { Html, Head, Preview, Body, Container, Section, Heading, Text, Hr } from '@react-email/components';
import * as React from 'react';
const AdminCancelRequestEmail = ({ orderId, customerName, reason, time }) => (React.createElement(Html, null,
    React.createElement(Head, null),
    React.createElement(Preview, null,
        "Y\u00EAu c\u1EA7u h\u1EE7y \u0111\u01A1n h\u00E0ng #",
        orderId,
        " t\u1EEB kh\u00E1ch h\u00E0ng"),
    React.createElement(Body, { style: { background: '#f9f9f9', fontFamily: 'Arial, sans-serif' } },
        React.createElement(Container, { style: { maxWidth: 600, margin: '0 auto', background: '#fff', borderRadius: 8, padding: 24 } },
            React.createElement(Section, { style: { textAlign: 'center' } },
                React.createElement(Heading, null, "Y\u00EAu c\u1EA7u h\u1EE7y \u0111\u01A1n h\u00E0ng"),
                React.createElement(Text, null,
                    "Kh\u00E1ch h\u00E0ng ",
                    React.createElement("b", null, customerName),
                    " v\u1EEBa g\u1EEDi y\u00EAu c\u1EA7u h\u1EE7y \u0111\u01A1n h\u00E0ng.")),
            React.createElement(Section, null,
                React.createElement(Text, null,
                    React.createElement("b", null, "M\u00E3 \u0111\u01A1n h\u00E0ng:"),
                    " ",
                    orderId),
                React.createElement(Text, null,
                    React.createElement("b", null, "L\u00FD do h\u1EE7y:"),
                    " ",
                    reason),
                React.createElement(Text, null,
                    React.createElement("b", null, "Th\u1EDDi gian y\u00EAu c\u1EA7u:"),
                    " ",
                    time)),
            React.createElement(Hr, null),
            React.createElement(Section, null,
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "Vui l\u00F2ng ki\u1EC3m tra v\u00E0 x\u1EED l\u00FD tr\u00EAn h\u1EC7 th\u1ED1ng qu\u1EA3n tr\u1ECB."),
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "M\u1ECDi th\u1EAFc m\u1EAFc li\u00EAn h\u1EC7: support@sportstore.com"))))));
export default AdminCancelRequestEmail;
