import { Html, Head, Preview, Body, Container, Section, Heading, Text, Link, Hr } from '@react-email/components';
import * as React from 'react';
const AdminNewOrderEmail = ({ shortId, createdAt, shippingAddress, items, totalPrice, paymentMethod, paymentStatus }) => (React.createElement(Html, null,
    React.createElement(Head, null),
    React.createElement(Preview, null,
        "Kh\u00E1ch h\u00E0ng ",
        shippingAddress.fullName,
        " v\u1EEBa t\u1EA1o \u0111\u01A1n h\u00E0ng m\u1EDBi #",
        shortId),
    React.createElement(Body, { style: { background: '#f9f9f9', fontFamily: 'Arial, sans-serif' } },
        React.createElement(Container, { style: { maxWidth: 650, margin: '0 auto', background: '#fff', borderRadius: 8, padding: 32 } },
            React.createElement(Section, { style: { textAlign: 'center', marginBottom: 24 } },
                React.createElement(Heading, { style: { color: '#2563eb', fontSize: 24 } }, "\u0110\u01A0N H\u00C0NG M\u1EDAI T\u1EEA KH\u00C1CH H\u00C0NG"),
                React.createElement(Text, { style: { fontSize: 18, margin: '12px 0' } },
                    React.createElement("b", null, shippingAddress.fullName),
                    " v\u1EEBa \u0111\u1EB7t \u0111\u01A1n h\u00E0ng #",
                    shortId),
                React.createElement(Text, { style: { color: '#666', fontSize: 14 } },
                    "Th\u1EDDi gian \u0111\u1EB7t: ",
                    typeof createdAt === 'string' ? createdAt : new Date(createdAt).toLocaleString('vi-VN'))),
            React.createElement(Section, null,
                React.createElement(Text, null,
                    React.createElement("b", null, "Th\u00F4ng tin kh\u00E1ch h\u00E0ng:")),
                React.createElement(Text, null,
                    "H\u1ECD t\u00EAn: ",
                    shippingAddress.fullName),
                React.createElement(Text, null,
                    "S\u0110T: ",
                    shippingAddress.phone),
                React.createElement(Text, null,
                    "\u0110\u1ECBa ch\u1EC9: ",
                    shippingAddress.address.street,
                    ", ",
                    shippingAddress.address.ward.name,
                    ", ",
                    shippingAddress.address.district.name,
                    ", ",
                    shippingAddress.address.province.name)),
            React.createElement(Hr, null),
            React.createElement(Section, null,
                React.createElement(Text, null,
                    React.createElement("b", null, "Chi ti\u1EBFt \u0111\u01A1n h\u00E0ng:")),
                React.createElement("table", { style: { width: '100%', borderCollapse: 'collapse', marginTop: 8, marginBottom: 8 } },
                    React.createElement("thead", null,
                        React.createElement("tr", { style: { background: '#f3f4f6' } },
                            React.createElement("th", { style: { padding: 8, border: '1px solid #eee', textAlign: 'left' } }, "S\u1EA3n ph\u1EA9m"),
                            React.createElement("th", { style: { padding: 8, border: '1px solid #eee', textAlign: 'center' } }, "SL"),
                            React.createElement("th", { style: { padding: 8, border: '1px solid #eee', textAlign: 'right' } }, "\u0110\u01A1n gi\u00E1"))),
                    React.createElement("tbody", null, items.map((item, idx) => (React.createElement("tr", { key: idx },
                        React.createElement("td", { style: { padding: 8, border: '1px solid #eee' } }, item.name),
                        React.createElement("td", { style: { padding: 8, border: '1px solid #eee', textAlign: 'center' } }, item.quantity),
                        React.createElement("td", { style: { padding: 8, border: '1px solid #eee', textAlign: 'right' } },
                            item.price.toLocaleString('vi-VN'),
                            "\u0111")))))),
                React.createElement(Text, { style: { textAlign: 'right', fontWeight: 'bold', fontSize: 16, marginTop: 8 } },
                    "T\u1ED5ng thanh to\u00E1n: ",
                    totalPrice.toLocaleString('vi-VN'),
                    "\u0111")),
            React.createElement(Section, null,
                React.createElement(Text, null,
                    React.createElement("b", null, "Ph\u01B0\u01A1ng th\u1EE9c thanh to\u00E1n:"),
                    " ",
                    paymentMethod),
                React.createElement(Text, null,
                    React.createElement("b", null, "Tr\u1EA1ng th\u00E1i thanh to\u00E1n:"),
                    " ",
                    paymentStatus)),
            React.createElement(Section, { style: { textAlign: 'center', margin: '24px 0' } },
                React.createElement(Link, { href: `https://admin.sportstore.com/orders/${shortId}`, style: { display: 'inline-block', background: '#2563eb', color: '#fff', padding: '12px 32px', borderRadius: 6, textDecoration: 'none', fontWeight: 600 } }, "Xem chi ti\u1EBFt \u0111\u01A1n h\u00E0ng tr\u00EAn trang qu\u1EA3n tr\u1ECB")),
            React.createElement(Hr, null),
            React.createElement(Section, { style: { textAlign: 'center', color: '#888', fontSize: 12 } },
                React.createElement(Text, null, "\u0110\u00E2y l\u00E0 email t\u1EF1 \u0111\u1ED9ng t\u1EEB h\u1EC7 th\u1ED1ng Sport Store. Vui l\u00F2ng kh\u00F4ng tr\u1EA3 l\u1EDDi email n\u00E0y."),
                React.createElement(Text, null, "M\u1ECDi th\u1EAFc m\u1EAFc li\u00EAn h\u1EC7: support@sportstore.com"))))));
export default AdminNewOrderEmail;
