import { Html, Head, Preview, Body, Container, Section, Heading, Text, Hr } from '@react-email/components';
import * as React from 'react';
const AdminProductLowStockEmail = ({ productName, productId, quantity, time }) => (React.createElement(Html, null,
    React.createElement(Head, null),
    React.createElement(Preview, null,
        "C\u1EA3nh b\u00E1o s\u1EA3n ph\u1EA9m s\u1EAFp h\u1EBFt: ",
        productName),
    React.createElement(Body, { style: { background: '#f9f9f9', fontFamily: 'Arial, sans-serif' } },
        React.createElement(Container, { style: { maxWidth: 600, margin: '0 auto', background: '#fff', borderRadius: 8, padding: 24 } },
            React.createElement(Section, { style: { textAlign: 'center' } },
                React.createElement(Heading, null, "C\u1EA3nh b\u00E1o s\u1EA3n ph\u1EA9m s\u1EAFp h\u1EBFt h\u00E0ng"),
                React.createElement(Text, null,
                    "S\u1EA3n ph\u1EA9m: ",
                    React.createElement("b", null, productName),
                    " (M\u00E3: ",
                    productId,
                    ")"),
                React.createElement(Text, null,
                    "S\u1ED1 l\u01B0\u1EE3ng c\u00F2n l\u1EA1i: ",
                    React.createElement("b", null, quantity)),
                React.createElement(Text, null,
                    "Th\u1EDDi gian c\u1EA3nh b\u00E1o: ",
                    time)),
            React.createElement(Hr, null),
            React.createElement(Section, null,
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "Vui l\u00F2ng ki\u1EC3m tra kho v\u00E0 nh\u1EADp th\u00EAm h\u00E0ng n\u1EBFu c\u1EA7n."),
                React.createElement(Text, { style: { fontSize: 12, color: '#888' } }, "M\u1ECDi th\u1EAFc m\u1EAFc li\u00EAn h\u1EC7: support@sportstore.com"))))));
export default AdminProductLowStockEmail;
