import { Body, Container, Head, Heading, Html, Img, Preview, Section, Text, Row, Column, Link, Hr, } from '@react-email/components';
import { Tailwind } from '@react-email/tailwind';
import * as React from 'react';
const NewOrderEmail = ({ shortId, fullName, createdAt, deliveryDate, items, subtotal, directDiscount, couponDiscount, shippingFee, totalPrice, shippingAddress, paymentMethod, paymentStatus, }) => {
    return (React.createElement(Html, null,
        React.createElement(Head, null),
        React.createElement(Preview, null,
            "X\u00E1c nh\u1EADn \u0111\u01A1n h\u00E0ng #",
            shortId,
            " t\u1EEB Sport Store"),
        React.createElement(Tailwind, null,
            React.createElement(Body, { className: "bg-gray-100 font-sans" },
                React.createElement(Container, { className: "mx-auto my-10 max-w-[650px] rounded-lg bg-white p-8 shadow-lg" },
                    React.createElement(Section, { className: "text-center" },
                        React.createElement(Img, { src: "https://sport-store.vercel.app/vju-logo-main.png", width: "160", height: "auto", alt: "Sport Store Logo", className: "mx-auto mb-7" }),
                        React.createElement(Heading, { className: "text-2xl font-bold text-gray-900" },
                            "Xin ch\u00E0o ",
                            fullName,
                            "!"),
                        React.createElement(Text, { className: "text-gray-600" },
                            "C\u1EA3m \u01A1n b\u1EA1n \u0111\u00E3 \u0111\u1EB7t h\u00E0ng t\u1EA1i",
                            ' ',
                            React.createElement("span", { className: "font-semibold text-blue-600" }, "Sport Store")),
                        React.createElement(Text, { className: "mt-2 text-sm text-gray-500" }, "Ch\u00FAng t\u00F4i \u0111\u00E3 nh\u1EADn \u0111\u01B0\u1EE3c \u0111\u01A1n h\u00E0ng c\u1EE7a b\u1EA1n v\u00E0 \u0111ang x\u1EED l\u00FD.")),
                    React.createElement(Section, { className: "mt-8 rounded-lg bg-blue-50 p-4" },
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-xs uppercase text-blue-600" }, "M\u00E3 \u0111\u01A1n h\u00E0ng"),
                                React.createElement(Text, { className: "text-lg font-semibold text-blue-800" },
                                    "#",
                                    shortId)),
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-xs uppercase text-blue-600" }, "Ng\u00E0y \u0111\u1EB7t h\u00E0ng"),
                                React.createElement(Text, { className: "text-lg font-medium text-blue-800" }, createdAt)),
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-xs uppercase text-blue-600" }, "D\u1EF1 ki\u1EBFn giao"),
                                React.createElement(Text, { className: "text-lg font-medium text-blue-800" }, deliveryDate)))),
                    React.createElement(Hr, { style: hr }),
                    React.createElement(Section, { className: "mt-8" },
                        React.createElement(Heading, { className: "mb-6 border-l-4 border-blue-500 pl-3 text-lg font-bold text-gray-900" }, "Chi ti\u1EBFt \u0111\u01A1n h\u00E0ng"),
                        React.createElement("div", { className: "overflow-x-auto" },
                            React.createElement("table", { className: "w-full" },
                                React.createElement("thead", null,
                                    React.createElement("tr", { className: "bg-gray-100" },
                                        React.createElement("th", { className: "p-4 text-left text-sm font-bold uppercase text-gray-600" }, "S\u1EA3n ph\u1EA9m"),
                                        React.createElement("th", { className: "p-4 text-center text-sm font-bold uppercase text-gray-600" }, "S\u1ED1 l\u01B0\u1EE3ng"),
                                        React.createElement("th", { className: "p-4 text-right text-sm font-bold uppercase text-gray-600" }, "Th\u00E0nh ti\u1EC1n"))),
                                React.createElement("tbody", null, items.map((item, index) => (React.createElement("tr", { key: index, className: "border-b border-gray-200 transition-colors hover:bg-gray-50" },
                                    React.createElement("td", { className: "p-4" },
                                        React.createElement("div", { className: "flex items-start gap-4" },
                                            React.createElement("div", { className: "h-20 w-20 flex-shrink-0 overflow-hidden rounded-lg bg-gray-100" },
                                                React.createElement(Img, { src: item.image, alt: item.name, className: "h-full w-full object-cover" })),
                                            React.createElement("div", null,
                                                React.createElement(Text, { className: "font-semibold text-gray-900" }, item.name),
                                                React.createElement(Text, { className: "mt-1 text-sm text-gray-500" },
                                                    item.price,
                                                    " / s\u1EA3n ph\u1EA9m")))),
                                    React.createElement("td", { className: "p-4 text-center font-medium text-gray-900" }, item.quantity),
                                    React.createElement("td", { className: "p-4 text-right font-semibold text-gray-900" }, item.price)))))))),
                    React.createElement(Section, { className: "mt-8 rounded-lg bg-gray-50 p-5" },
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-sm text-gray-600" }, "T\u1ED5ng ti\u1EC1n h\u00E0ng:")),
                            React.createElement(Column, { align: "right" },
                                React.createElement(Text, { className: "text-sm font-medium text-gray-900" }, subtotal))),
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-sm text-gray-600" }, "Gi\u1EA3m gi\u00E1 tr\u1EF1c ti\u1EBFp:")),
                            React.createElement(Column, { align: "right" },
                                React.createElement(Text, { className: "text-sm font-medium text-red-600" },
                                    "-",
                                    directDiscount))),
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-sm text-gray-600" }, "M\u00E3 gi\u1EA3m gi\u00E1:")),
                            React.createElement(Column, { align: "right" },
                                React.createElement(Text, { className: "text-sm font-medium text-red-600" },
                                    "-",
                                    couponDiscount))),
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-sm text-gray-600" }, "Ph\u00ED v\u1EADn chuy\u1EC3n:")),
                            React.createElement(Column, { align: "right" },
                                React.createElement(Text, { className: "text-sm font-medium text-gray-900" }, shippingFee))),
                        React.createElement(Row, null,
                            React.createElement(Column, null,
                                React.createElement(Text, { className: "text-base font-bold text-gray-900" }, "T\u1ED5ng thanh to\u00E1n:")),
                            React.createElement(Column, { align: "right" },
                                React.createElement(Text, { className: "text-lg font-bold text-blue-600" }, totalPrice)))),
                    React.createElement(Hr, { style: hr }),
                    React.createElement(Section, { className: "mt-8" },
                        React.createElement(Heading, { className: "mb-4 text-lg font-semibold text-gray-900" }, "Th\u00F4ng tin giao h\u00E0ng"),
                        React.createElement(Text, { className: "text-gray-700" }, shippingAddress)),
                    React.createElement(Section, { className: "mt-8" },
                        React.createElement(Heading, { className: "mb-4 text-lg font-semibold text-gray-900" }, "Ph\u01B0\u01A1ng th\u1EE9c thanh to\u00E1n"),
                        React.createElement(Text, { className: "text-gray-700" }, paymentMethod),
                        React.createElement(Text, { className: "text-gray-700" },
                            "Tr\u1EA1ng th\u00E1i: ",
                            paymentStatus)),
                    React.createElement(Section, { className: "mt-8 text-center" },
                        React.createElement(Link, { href: `https://sport-store.vercel.app/orders/${shortId}`, className: "inline-block rounded-full bg-blue-600 px-8 py-3 text-white shadow-lg transition-colors hover:bg-blue-700" }, "Xem chi ti\u1EBFt \u0111\u01A1n h\u00E0ng")),
                    React.createElement(Section, { className: "mt-8 rounded-lg bg-gray-50 p-6 text-center" },
                        React.createElement(Heading, { className: "mb-4 text-lg font-semibold text-gray-900" }, "H\u1ED7 tr\u1EE3 kh\u00E1ch h\u00E0ng"),
                        React.createElement("div", { className: "flex flex-col items-center gap-3" },
                            React.createElement("div", { className: "flex items-center" },
                                React.createElement("div", { className: "mr-3 flex h-8 w-8 items-center justify-center rounded-full bg-blue-100" },
                                    React.createElement("svg", { className: "h-4 w-4 text-blue-500", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2" },
                                        React.createElement("path", { d: "M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" }))),
                                React.createElement(Link, { href: "mailto:support@sportstore.com", className: "text-blue-500" }, "support@sportstore.com")),
                            React.createElement("div", { className: "flex items-center" },
                                React.createElement("div", { className: "mr-3 flex h-8 w-8 items-center justify-center rounded-full bg-blue-100" },
                                    React.createElement("svg", { className: "h-4 w-4 text-blue-500", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2" },
                                        React.createElement("path", { d: "M3 5.5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5.5z" }))),
                                React.createElement(Link, { href: "tel:0362195258", className: "text-blue-500" }, "0362195258")))),
                    React.createElement(Section, { className: "mt-8 text-center" },
                        React.createElement(Text, { className: "text-sm text-gray-500" }, "\u00A9 2025 Sport Store. T\u1EA5t c\u1EA3 c\u00E1c quy\u1EC1n \u0111\u01B0\u1EE3c b\u1EA3o l\u01B0u."),
                        React.createElement(Text, { className: "mt-1 text-xs text-gray-500" }, "Email n\u00E0y \u0111\u01B0\u1EE3c g\u1EEDi t\u1EF1 \u0111\u1ED9ng, vui l\u00F2ng kh\u00F4ng tr\u1EA3 l\u1EDDi.")))))));
};
export default NewOrderEmail;
const hr = {
    borderColor: '#e6ebf1',
    margin: '20px 0',
};
