import { Body, Container, Head, Heading, Html, Img, Preview, Section, Text, Link, Hr, } from '@react-email/components';
import { Tailwind } from '@react-email/tailwind';
import * as React from 'react';
const ProfileUpdateEmail = ({ name = 'Khách hàng', time = new Date().toLocaleString('vi-VN'), changes = [] }) => {
    return (React.createElement(Html, null,
        React.createElement(Head, null),
        React.createElement(Preview, null, "Th\u00F4ng tin t\u00E0i kho\u1EA3n c\u1EE7a b\u1EA1n \u0111\u00E3 \u0111\u01B0\u1EE3c c\u1EADp nh\u1EADt"),
        React.createElement(Tailwind, null,
            React.createElement(Body, { className: "bg-gray-100 font-sans" },
                React.createElement(Container, { className: "mx-auto my-10 max-w-[600px] rounded-lg bg-white p-8 shadow-lg" },
                    React.createElement(Section, { className: "text-center" },
                        React.createElement(Img, { src: "https://sport-store.vercel.app/vju-logo-main.png", width: "160", height: "auto", alt: "Sport Store Logo", className: "mx-auto mb-6" }),
                        React.createElement(Heading, { className: "text-2xl font-bold text-gray-900" }, "Th\u00F4ng tin t\u00E0i kho\u1EA3n \u0111\u00E3 \u0111\u01B0\u1EE3c c\u1EADp nh\u1EADt"),
                        React.createElement(Text, { className: "text-gray-600" },
                            "Xin ch\u00E0o ",
                            React.createElement("span", { className: "font-semibold" }, name),
                            ","),
                        React.createElement(Text, { className: "mt-2 text-gray-600" },
                            "Th\u00F4ng tin t\u00E0i kho\u1EA3n c\u1EE7a b\u1EA1n t\u1EA1i Sport Store \u0111\u00E3 \u0111\u01B0\u1EE3c c\u1EADp nh\u1EADt th\u00E0nh c\u00F4ng v\u00E0o l\u00FAc ",
                            time,
                            ".")),
                    changes.length > 0 ? (React.createElement(Section, { className: "mt-8 rounded-lg border border-gray-200 bg-white p-6" },
                        React.createElement(Heading, { className: "mb-4 text-lg font-semibold text-gray-900" }, "Th\u00F4ng tin \u0111\u00E3 c\u1EADp nh\u1EADt"),
                        React.createElement("table", { className: "w-full" },
                            React.createElement("tbody", null, changes.map((change, index) => (React.createElement("tr", { key: index, className: index % 2 === 0 ? 'bg-gray-50' : 'bg-white' },
                                React.createElement("td", { className: "border-b border-gray-200 px-4 py-2 text-sm font-medium text-gray-600" }, change.field),
                                React.createElement("td", { className: "border-b border-gray-200 px-4 py-2 text-sm text-gray-900" }, change.value)))))))) : (React.createElement(Section, { className: "mt-8 rounded-lg bg-green-50 p-6" },
                        React.createElement(Text, { className: "text-center text-green-700" },
                            React.createElement("strong", null, "C\u1EADp nh\u1EADt th\u00F4ng tin th\u00E0nh c\u00F4ng!")))),
                    React.createElement(Section, { className: "mt-8 rounded-lg bg-yellow-50 p-4" },
                        React.createElement(Text, { className: "text-sm text-yellow-700" },
                            React.createElement("strong", null, "L\u01B0u \u00FD b\u1EA3o m\u1EADt:"),
                            " N\u1EBFu b\u1EA1n kh\u00F4ng th\u1EF1c hi\u1EC7n thay \u0111\u1ED5i n\u00E0y, vui l\u00F2ng li\u00EAn h\u1EC7 ngay v\u1EDBi ch\u00FAng t\u00F4i.")),
                    React.createElement(Section, { className: "mt-8 text-center" },
                        React.createElement(Link, { href: "https://sport-store.vercel.app/user/profile", className: "inline-block rounded-lg bg-blue-600 px-6 py-3 text-center font-medium text-white shadow-sm hover:bg-blue-700" }, "Xem t\u00E0i kho\u1EA3n c\u1EE7a t\u00F4i"),
                        React.createElement(Text, { className: "mt-6 text-sm text-gray-600" },
                            "C\u1EA7n h\u1ED7 tr\u1EE3? H\u00E3y li\u00EAn h\u1EC7 v\u1EDBi ch\u00FAng t\u00F4i qua email: ",
                            React.createElement(Link, { href: "mailto:support@sportstore.com", className: "text-blue-600 underline" }, "support@sportstore.com"))),
                    React.createElement(Hr, { className: "my-8 border-gray-200" }),
                    React.createElement(Section, { className: "text-center" },
                        React.createElement(Text, { className: "text-xs text-gray-500" }, "\u00A9 2025 Sport Store. T\u1EA5t c\u1EA3 c\u00E1c quy\u1EC1n \u0111\u01B0\u1EE3c b\u1EA3o l\u01B0u."),
                        React.createElement(Text, { className: "mt-1 text-xs text-gray-500" }, "\u0110\u1ECBa ch\u1EC9: 97 \u0110\u01B0\u1EDDng V\u00F5 V\u0103n T\u1EA7n, Ph\u01B0\u1EDDng 6, Qu\u1EADn 3, Th\u00E0nh ph\u1ED1 H\u1ED3 Ch\u00ED Minh")))))));
};
export default ProfileUpdateEmail;
